### ISSUE TITLE
ReplyKeyboardMarkup.Keyboard incorrect type

### ISSUE THREAD

**Issue by mproved** [mymmrac/go-telegram-bot-api#1]
"ReplyKeyboardMarkup.Keyboard" type is []KeyboardButton, but it's supposed be [][]KeyboardButton

<html><body>

Field | Type | Description
-- | -- | --
keyboard | Array of Array of KeyboardButton | Array of button rows, each represented by an Array of KeyboardButton objects

</body>

**Comment by mymmrac** [comment]
Fixed in v0.1.4, please check if all works as expected and close the issue.

Really, thanks for reporting such things
